pipeline:
  build:
    image: nossas/bonde-test
    commands:
      - yarn
      - yarn test

  publish:
    image: plugins/docker
    repo: nossas/bonde-test
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
